name: test-readme
on: [push]
jobs:
  test-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Clone tuttest
        uses: actions/checkout@v4
        with:
          path: tuttest
          repository: antmicro/tuttest
      - name: Install tuttest
        run: pip install ./tuttest
      - name: Checkout gerber2ems
        uses: actions/checkout@v4
        with:
          path: main
      - name: Run installation with tuttest
        run: |
          cd ./main
          tuttest README.md unnamed0 | bash -
          tuttest README.md unnamed1 | bash -
          tuttest README.md unnamed2 | bash -
          tuttest README.md unnamed3 | bash -
          tuttest README.md unnamed4 | bash -
          tuttest README.md unnamed5 | bash -
      - name: Run example with tuttest
        run: |
          cd ./main
          tuttest README.md run-example | bash -
